default: &default
  public_root_path: public
  public_output_path: avo-packs

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

development:
  <<: *default

test:
  <<: *default
  compile: true

production:
  <<: *default

  # Cache manifest.json for performance
  cache_manifest: true
