name: Reviewdog
on: [pull_request]
jobs:
  standardrb:
    name: runner / standardrb
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: standardrb
        uses: SennaLabs/action-standardrb@v0.0.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          rubocop_version: 0.1.6
          rubocop_flags: --format progress

  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
